name: inclasshomework
description: Creating assignments in class

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  google_fonts: ^0.3.10
  http: any
  html: any
  grouped_buttons: ^1.0.4
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

